project_name: x-twitter-scraper
version: 2

metadata:
  mod_timestamp: '{{ .CommitTimestamp }}'

before:
  hooks:
    - mkdir -p completions
    - sh -c "go run ./cmd/x-twitter-scraper @completion bash > completions/x-twitter-scraper.bash"
    - sh -c "go run ./cmd/x-twitter-scraper @completion zsh > completions/x-twitter-scraper.zsh"
    - sh -c "go run ./cmd/x-twitter-scraper @completion fish > completions/x-twitter-scraper.fish"
    - sh -c "go run ./cmd/x-twitter-scraper @manpages -o man"

builds:
  - id: macos
    goos: [darwin]
    goarch: [amd64, arm64]
    binary: '{{ .ProjectName }}'
    main: ./cmd/x-twitter-scraper
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags: [-trimpath]
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'

  - id: linux
    goos: [linux]
    goarch: ['386', arm, amd64, arm64]
    env:
      - CGO_ENABLED=0
    binary: '{{ .ProjectName }}'
    main: ./cmd/x-twitter-scraper
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags: [-trimpath]
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'

  - id: windows
    goos: [windows]
    goarch: ['386', amd64, arm64]
    binary: '{{ .ProjectName }}'
    main: ./cmd/x-twitter-scraper
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags: [-trimpath]
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'

archives:
  - id: linux-archive
    ids: [linux]
    name_template: '{{ .ProjectName }}_{{ .Version }}_linux_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    formats: [tar.gz]
    builds_info:
      mtime: '{{ .CommitDate }}'
    files:
      - src: completions/*
        info:
          mtime: '{{ .CommitDate }}'
      - src: man/*/*
        info:
          mtime: '{{ .CommitDate }}'
      - src: LICENSE
        info:
          mtime: '{{ .CommitDate }}'
      - src: LICENSES/BSD-3-Clause.txt
        info:
          mtime: '{{ .CommitDate }}'
      - src: THIRD_PARTY_NOTICES.md
        info:
          mtime: '{{ .CommitDate }}'
  - id: macos-archive
    ids: [macos]
    name_template: '{{ .ProjectName }}_{{ .Version }}_macos_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    formats: [zip]
    builds_info:
      mtime: '{{ .CommitDate }}'
    files:
      - src: completions/*
        info:
          mtime: '{{ .CommitDate }}'
      - src: man/*/*
        info:
          mtime: '{{ .CommitDate }}'
      - src: LICENSE
        info:
          mtime: '{{ .CommitDate }}'
      - src: LICENSES/BSD-3-Clause.txt
        info:
          mtime: '{{ .CommitDate }}'
      - src: THIRD_PARTY_NOTICES.md
        info:
          mtime: '{{ .CommitDate }}'
  - id: windows-archive
    ids: [windows]
    name_template: '{{ .ProjectName }}_{{ .Version }}_windows_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    formats: [zip]
    builds_info:
      mtime: '{{ .CommitDate }}'
    files:
      - src: completions/*
        info:
          mtime: '{{ .CommitDate }}'
      - src: man/*/*
        info:
          mtime: '{{ .CommitDate }}'
      - src: LICENSE
        info:
          mtime: '{{ .CommitDate }}'
      - src: LICENSES/BSD-3-Clause.txt
        info:
          mtime: '{{ .CommitDate }}'
      - src: THIRD_PARTY_NOTICES.md
        info:
          mtime: '{{ .CommitDate }}'

snapshot:
  version_template: '{{ .Tag }}-next'

release:
  draft: true

nfpms:
  - license: Apache-2.0
    maintainer: support@xquik.com
    bindir: /usr
    mtime: '{{ .CommitDate }}'
    formats:
      - apk
      - deb
      - rpm
      - termux.deb
      - archlinux
    contents:
      - src: man/man1/*.1.gz
        dst: /usr/share/man/man1/
        file_info:
          mtime: '{{ .CommitDate }}'
      - src: LICENSE
        dst: /usr/share/doc/x-twitter-scraper/LICENSE
        file_info:
          mtime: '{{ .CommitDate }}'
      - src: LICENSES/BSD-3-Clause.txt
        dst: /usr/share/doc/x-twitter-scraper/BSD-3-Clause.txt
        file_info:
          mtime: '{{ .CommitDate }}'
      - src: THIRD_PARTY_NOTICES.md
        dst: /usr/share/doc/x-twitter-scraper/THIRD_PARTY_NOTICES.md
        file_info:
          mtime: '{{ .CommitDate }}'
