#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

cd "$(dirname "$0")/.."

echo "==> Unlinking with local directory"
go mod edit -dropreplace github.com/Xquik-dev/x-twitter-scraper-go
